empleado-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 12:48:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema ejemplo_producto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ejemplo_producto` ;

-- -----------------------------------------------------
-- Schema ejemplo_producto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ejemplo_producto` ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema2
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema3
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`timestamps` ;

CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);

USE `ejemplo_producto` ;

-- -----------------------------------------------------
-- Table `ejemplo_producto`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`CLIENTE` (
  `dni` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `tlf` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`PROVEEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`PROVEEDOR` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`PROVEEDOR` (
  `nif` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`PRODUCTO` (
  `idPRODUCTO` INT NOT NULL,
  `PROVEEDOR_nif` INT NOT NULL,
  PRIMARY KEY (`idPRODUCTO`),
  INDEX `fk_PRODUCTO_PROVEEDOR1_idx` (`PROVEEDOR_nif` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_nif`)
    REFERENCES `ejemplo_producto`.`PROVEEDOR` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`COMPRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`COMPRA` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`COMPRA` (
  `CLIENTE_dni` INT NOT NULL,
  `PRODUCTO_codigo` INT NOT NULL,
  `PRODUCTO_nombre` VARCHAR(45) NOT NULL,
  `PRODUCTO_idPRODUCTO` INT NOT NULL,
  PRIMARY KEY (`CLIENTE_dni`, `PRODUCTO_codigo`, `PRODUCTO_nombre`),
  INDEX `fk_CLIENTE_has_PRODUCTO_CLIENTE_idx` (`CLIENTE_dni` ASC) VISIBLE,
  INDEX `fk_COMPRA_PRODUCTO1_idx` (`PRODUCTO_idPRODUCTO` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_has_PRODUCTO_CLIENTE`
    FOREIGN KEY (`CLIENTE_dni`)
    REFERENCES `ejemplo_producto`.`CLIENTE` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMPRA_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_idPRODUCTO`)
    REFERENCES `ejemplo_producto`.`PRODUCTO` (`idPRODUCTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `ejemplo_producto` ;

-- -----------------------------------------------------
-- Placeholder table for view `ejemplo_producto`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`view1` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `ejemplo_producto`.`view2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`view2` (`id` INT);

-- -----------------------------------------------------
-- View `ejemplo_producto`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`view1`;
DROP VIEW IF EXISTS `ejemplo_producto`.`view1` ;
USE `ejemplo_producto`;


-- -----------------------------------------------------
-- View `ejemplo_producto`.`view2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`view2`;
DROP VIEW IF EXISTS `ejemplo_producto`.`view2` ;
USE `ejemplo_producto`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
